WEBHOOK_PASSPHRASE = "INSERT PASSPHRASE HERE"

API_KEY = "INSERT KEY HERE"
API_SECRET = "INSERT KEY HERE"

REPORT = True
DISCORD_ERROR_ID = "INSERT CHANNEL ID"
DISCORD_TRANSACTION_ID = "INSERT CHANNEL ID"
DISCORD_ERROR_LINK = f"https://discord.com/api/v9/channels/{DISCORD_ERROR_ID}/messages"
DISCORD_TRANSACTION_LINK = f"https://discord.com/api/v9/channels/{DISCORD_TRANSACTION_ID}/messages"

DISCORD_HEADER = {"authorization": "MzY5MDQ5NjU3Mjc3NTQ2NDk2.YORUJQ.uMGWbdQVG9X9_j6NDxY7URUtn90"}

LEVERAGE = 1.95

MAX_DRAWDOWN = 4.1

BALANCE = 20

QUANTITY = 0.004